version: '3.8'

# 开发环境覆盖配置
# 使用方式: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./manage-backend:/app
      - /app/bin
    command: ["air", "-c", ".air.toml"]

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./manage-frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
