# 开发环境配置
environment: development
log_level: warn

# 开发环境日志配置：控制台输出，便于调试
log:
  level: warn
  format: console # 彩色控制台输出
  output_path: logs/prod.log # 仅输出到控制台
  max_size: 100
  max_backups: 3
  max_age: 7
  compress: false

database:
  host: prod-db.example.com
  port: 5432
  user: prod_user
  password: ${DB_PASSWORD}
  name: go_manage_starter
  schema: manage_prod

redis:
  host: prod-redis.example.com
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0

jwt:
  secret: ${JWT_SECRET}
  expire_time: 24 # Deprecated: for backward compatibility
  access_token_expire: 30 # Access token expiration in minutes
  refresh_token_expire: 720 # Refresh token expiration in hours (30 days)
